Classifieds/Ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('register/', views.register, name = 'register'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),


]

Classifieds/Classifieds/urls.py
import os

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('Ads.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.png',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

Classifieds/Ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from taggit.managers import TaggableManager


# Create your models here.

class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Comment', related_name='ads_comments')

    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Fav', related_name='favorite_ads')

    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True, help_text='The MIMEType of the file')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    text = models.TextField(validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")])

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'
    
class Fav(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='fav_users')

    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self):
        return '%s likes %s'%(self.user.username, self.ad.title[:10])

Classifieds/Ads/forms.py
from django import forms
from Ads.models import Ad
from django.core.files.uploadedfile import InMemoryUploadedFile
from Ads.humanize import naturalsize
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = Ad
        fields = ['title', 'price', 'tags', 'text', 'picture']

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")
            
    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()

        return instance
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

Classifieds/Ads/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.humanize.templatetags.humanize import naturaltime

from django.db.models import Q

from .forms import CreateForm, CommentForm, UserRegistrationForm
from .models import Ad, Comment, Fav
from .owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

# Create your views here.
def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            ctx = {'new_user': new_user}
            return render(request,'registration/register_done.html', ctx)
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form': user_form})


class AdListView(OwnerListView):
    model = Ad
    template_name = "ads/ad_list.html"

    def get(self, request):
        strval = request.GET.get("search", False)
        favorites = list()
        if strval:
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            query.add(Q(tags__name__in=[strval]), Q.OR)
            ad_list = Ad.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            ad_list = Ad.objects.all().order_by('-updated_at')[:10]

        for obj in ad_list:
            obj.natural_updated = naturaltime(obj.updated_at)

        if request.user.is_authenticated:
            rows = request.user.favorite_ads.values('id')
            favorites = [ row['id'] for row in rows ]

        ctx = {'ad_list' : ad_list, 'search': strval, 'favorites' : favorites}
        return render(request, self.template_name, ctx)
class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = "ads/ad_detail.html"
    def get(self, request, pk):
        x = Ad.objects.get(id=pk)
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')
        comment_form = CommentForm()
        ctx = { 'ad': x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, ctx)

class AdCreateView(LoginRequiredMixin, View):
    template_name = "ads/ad_form.html"
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)
    
    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)
        
        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        form.save_m2m()
        return redirect(self.success_url)

from django.views.generic.edit import UpdateView

class AdUpdateView(OwnerUpdateView):
    template_name = 'ads/ad_form.html'
    model = Ad
    fields = ['title', 'price', 'tags', 'text']
    success_url = reverse_lazy('ads:all')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ad = self.get_object()
        form = CreateForm(instance=ad)  # Populate the form with existing data
        context['form'] = form
        return context

    def form_valid(self, form):
        ad = form.save(commit=False)
        ad.save()
        form.save_m2m()  # Save the tags
        return super().form_valid(form)


class AdDeleteView(OwnerDeleteView):
    model = Ad

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        a = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=a)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))

class CommentDeleteView(LoginRequiredMixin, View):
    model = Comment
    template_name = "ads/comment_delete.html"
    success_url = reverse_lazy('ads:all')

    def get_success_url(self):
        forum = self.object.ad
        return reverse('ads:ad_detail', args=[Ad.id])

def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        a = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=a)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        a = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=a).delete()
        except Ad.DoesNotExist as e:
            pass

        return HttpResponse()

Classifieds/Ads/templates/ads/ad_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Ad</h1>

<p>Are you sure you want to delete the ad: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

Classifieds/Ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
<h1>
  {{ ad.title }}
</h1>
{% if ad.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ ad.updated_at|naturaltime }})
{% if ad.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
{% if ad.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'ads:ad_picture' ad.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ ad.text }}
</p>
<p>
  {{ ad.price }}
</p>
{% if ad.tags.all %}
<p>Tags: 
  {% for tag in ad.tags.all %}
  <span style="border:1px grey solid; background-color: LightGreen;">{{ tag }}</span>
  {% endfor %}
</p>
{% endif %}
{% if user.is_authenticated %}
<br clear="all">
<p>
  {% load crispy_forms_tags %}
  <form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
      {% csrf_token %}
      {{ comment_form|crispy }}
  <input type="submit" value="Submit">
  <button type="button" id="cancelButton">Cancel</button>
  </form>
  </p>
  {% endif %}
  {% for comment in comments %}
  <p>{{ comment.owner }} : {{ comment.text }} 
  ({{ comment.updated_at|naturaltime }})
  {% if user == comment.owner %}
  <a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
  {% endif %}
  </p>
  {% endfor %}
  {% endblock %}
  <script>
    document.getElementById("cancelButton").addEventListener("click", function() {
        window.location.href = "{% url 'ads:all' %}";
    });
    </script>

Classifieds/Ads/templates/ads/ad_form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" name="submit_action" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
{% endblock %}
<script>
document.getElementById("cancelButton").addEventListener("click", function() {
    window.location.href = "{% url 'ads:all' %}";
});
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
    var file = $('#if_{{ form.upload_field_name }}')[0].files[0];
    if (file && file.size > {{ form.max_upload_limit }} ) {
      alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
    return false;
    }
  }
});
</script>

Classifieds/Ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Classified Ads</h1>
<div style="float:right">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
    <form>
      <input type="text" placeholder="Search.." name="search"
      {% if search %} value="{{ search }}" {% endif %}
      >
      <button type="submit"><i class="fa fa-search"></i></button>
    <a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
    </form>
    </div>
<p>
    {% if ad_list %}
    <ul>
        {% for ad in ad_list %}
        <li>
          <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title }}</a>
          {% if ad.owner_id == user.id %}
          (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
          <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
          {% endif %}
          {% if user.is_authenticated %}
          <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
          <a href="#" onclick=
              "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
              {% if ad.id not in favorites %} style="display: none;" {% endif %}
              id="favorite_star_{{ad.id}}">
          <span class="fa-stack" style="vertical-align: middle;">
          <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
          <i class="fa fa-star-o fa-stack-1x"></i>
          </span>
          </a>
          <!-- the second href -->
          <a href="#" onclick=
               "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
              {% if ad.id in favorites %} style="display: none;" {% endif %}
              id="unfavorite_star_{{ad.id}}">
          <span class="fa-stack" style="vertical-align: middle;">
          <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
          <i class="fa fa-star-o fa-stack-1x"></i>
          </span>
          </a>
          {% endif %}
      </li>
        {% endfor %}
      </ul>
      {% else %}
  <p>There are no ads in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'ads:ad_create' %}">Add an Article</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
{% endif %}
</p>
<script>
  function favPost(url, ad_id) {
      console.log('Requesting JSON');
      $.post(url, {},  function(rowz){
          console.log(url, 'finished');
          $("#unfavorite_star_"+ad_id).toggle();
          $("#favorite_star_"+ad_id).toggle();
      }).fail(function(xhr) {
          alert('Url failed with '+xhr.status+' '+url);
      });
  }
  </script>
  {% endblock %}

  

Classifieds/Ads/templates/ads/comment_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}